name: CODECOV TEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions: read-all
jobs:
  Deploy_codecov:
    runs-on: ubuntu-latest

    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env: 
       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
   
      

