name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  id-token: write
  contents: read

jobs:
  Build_image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
    - name: Build the Docker image
      run: docker build . -t pabloten56/test-api
    - name: Push the Docker image (to Docker Hub)
      run: docker push pabloten56/test-api
      
  Deploy_image:
    runs-on: ubuntu-latest
    needs: Build_image
    steps:
      - name: 'Az CLI login using OIDC'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Run az restart'
        run: |
          az webapp restart --name test-silver-river-definitive --resource-group test-silver-river-definitive_group
          
    # https://dev.to/pwd9000/bk-1iij
