name: Learning GitHub Script V2
on:
  issues:
    types: [opened]
jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Comment on new issue
      uses: actions/github-script@0.8.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
            github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!"
            })
    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v2
      with:
        token: ${{ secrets.PAT }}
        project-name: TEST SILVER RIVER
        column-name: Todo
 
